---
- name: Install and start Apache web server
  hosts: node1.lab.example.com
  become: true
  tasks:
    - name: Install Apache package
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Ensure Apache is running and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Create simple index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          Hello from Ansible! Web server configured successfully.
